---
- hosts: shelves
  remote_user: root
  vars:
    docker:
      config_dir: /etc/docker
    secret:
      database:
        password: 
        root_password:
      google:
        oauth:
          id:
          secret:
      github:
        oauth:
          id:
          secret:
  vars_files:
    - secrets.yml
  roles:
    - prometheus
    - nginx_proxy
    - shelves_backend
    - shelves_frontend

