---
- hosts: shelves
  remote_user: root
  vars:
    MARIADB_PASSWORD: password
    MARIADB_DATABASE: shelves
    MARIADB_USERNAME: shelves
  roles:
    - docker
    - prometheus
    - mariadb
    - memcached
    - shelves_backend
    - shelves_frontend

