ALTER TABLE numeric_property CHANGE COLUMN base base0 int;
ALTER TABLE numeric_property ADD COLUMN base varchar(5) not null default 'ATTO';
UPDATE numeric_property set base = "ATTO" where base0 = 0;
UPDATE numeric_property set base = "FEMTO" where base0 = 1;
UPDATE numeric_property set base = "PICO" where base0 = 2;
UPDATE numeric_property set base = "NANO" where base0 = 3;
UPDATE numeric_property set base = "MICRO" where base0 = 4;
UPDATE numeric_property set base = "MILLI" where base0 = 5;
UPDATE numeric_property set base = "NONE" where base0 = 6;
UPDATE numeric_property set base = "DECA" where base0 = 7;
UPDATE numeric_property set base = "HECTO" where base0 = 8;
UPDATE numeric_property set base = "KILO" where base0 = 9;
UPDATE numeric_property set base = "MEGA" where base0 = 10;
UPDATE numeric_property set base = "GIGA" where base0 = 11;
UPDATE numeric_property set base = "TERA" where base0 = 12;
UPDATE numeric_property set base = "PETA" where base0 = 13;
UPDATE numeric_property set base = "EXA" where base0 = 14;
UPDATE numeric_property set base = "ZETTA" where base0 = 15;
UPDATE numeric_property set base = "YOTTA" where base0 = 16;
UPDATE numeric_property set base = "KIBI" where base0 = 17;
UPDATE numeric_property set base = "MIBI" where base0 = 18;
UPDATE numeric_property set base = "GIBI" where base0 = 19;
UPDATE numeric_property set base = "TIBI" where base0 = 20;
UPDATE numeric_property set base = "PIBI" where base0 = 21;
ALTER TABLE numeric_property DROP COLUMN base0;
